### ISSUE TITLE
Disallow changing id in account_update

### ISSUE THREAD

**Issue by wangshuangkc** [HansiMou/nyu-devops-BankSystem#16]
As a Banker
I need a way to update an account balance
So that I can do it when the account balance changes without modifying the other info

Assumptions:

Add a URL of /accounts/id by PUT
URL should return the info with new balance of account id.

Acceptance Criteria:
When I call the PUT URL/accounts/id
It should return the account info of id with new balance and old other info as a JSON string in the format:

{
  active: <a>,
  id:<i>
  name: <k>,
  balance: <n>
}
Where "n" is the balance, "k" is the name, "i" is the account id, "a" is whether the account is active

**Comment by wangshuangkc** [comment]
I can think of two cases that the account name is changed:
1. the owner has a new name: actually all the accounts under his name should change, which is impossible as we have duplicate names
2. the account is assigned to another person: vote for disallowing this case

Any other cases that you may think of about changing account name? @HansiMou @sarahhh000 @RobinRule

**Comment by sarahhh000** [comment]
First, there could be duplicate names since there might be multiple people called "Ming Li", and it might not be a good idea to name them as "Ming Li1", "Ming Li2" ...

About the name changing access, I just thought there might be some name change situation, and name changing won't affect our system. I support the idea that if it won't influence the database's functionality, we should give users more access to modify their data.
